// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {ERC1967Proxy} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import {ERC1967Utils} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Utils.sol";
import {ProxyAdmin} from "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";
import {
    ITransparentUpgradeableProxy,
    TransparentUpgradeableProxy
} from "@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol";
import {Initializable} from "@openzeppelin/contracts/proxy/utils/Initializable.sol";
import {UUPSUpgradeable} from "@openzeppelin/contracts/proxy/utils/UUPSUpgradeable.sol";
import {
    NamespacedSentinelModuleV1,
    NamespacedSentinelModuleV2,
    SentinelModuleExtensionNamespace,
    SentinelModuleNamespace,
    SentinelValues
} from "../../contracts/mocks/NamespacedSentinelModule.sol";

/// @dev Exposes the sentinel namespace constants so they can be compared with the formula.
contract SentinelSlotProbe is SentinelModuleNamespace, SentinelModuleExtensionNamespace {
    function sentinelSlot() external pure returns (bytes32) {
        return SENTINEL_MODULE_STORAGE_LOCATION;
    }

    function extensionSlot() external pure returns (bytes32) {
        return SENTINEL_MODULE_EXTENSION_STORAGE_LOCATION;
    }
}

/// @dev Unsafe upgrade fixture: `linearValue` and `linearTag` are swapped relative to V1 (the
///      shape of an inherited-layout reorder). The static checker rejects this transition; the
///      sentinel test below shows the corruption it prevents.
contract ReorderedSentinelModule is Initializable, UUPSUpgradeable, SentinelModuleNamespace {
    address public owner;
    bytes32 public linearTag;
    uint256 public linearValue;
    mapping(uint256 => uint256) public linearValues;
    uint256[46] private __gap;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    function _authorizeUpgrade(address) internal view override {
        require(msg.sender == owner, "not owner");
    }
}

/// @dev Unsafe upgrade fixture: implementation code that writes the ERC-1967 implementation slot
///      (reserved-slot overwrite). The static checker rejects any module referencing that slot.
contract ReservedSlotClobberingModule is Initializable, UUPSUpgradeable {
    address public owner;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    function clobberImplementationSlot(address value) external {
        bytes32 slot = ERC1967Utils.IMPLEMENTATION_SLOT;
        assembly {
            sstore(slot, value)
        }
    }

    function _authorizeUpgrade(address) internal view override {
        require(msg.sender == owner, "not owner");
    }
}

/**
 * @title StorageNamespaceCollisionTest (V2-SC-159)
 * @notice Solidity-side evidence for the storage namespace manifest
 *         (`storage-layouts/namespace-manifest.json`, generated by
 *         `scripts/check-storage-namespaces.mjs`):
 *         1. the ERC-1967 reserved slots in the manifest are OpenZeppelin's constants and their
 *            `keccak256(id) - 1` derivation;
 *         2. every ERC-7201 namespace slot in the manifest recomputes in Solidity, is 256-aligned
 *            and never equals a reserved slot; every module's computed slots are distinct;
 *         3. the manifest's Initializable namespace is the slot OpenZeppelin actually writes;
 *         4. sentinel values written before a UUPS or transparent upgrade read back unchanged,
 *            and implementation writes never touch the proxy implementation/admin/beacon slots;
 *         5. the unsafe transitions the checker rejects really corrupt state (reorder) or brick
 *            the proxy (reserved-slot overwrite).
 */
contract StorageNamespaceCollisionTest is Test {
    string internal constant MANIFEST_PATH = "storage-layouts/namespace-manifest.json";
    string internal constant FROZEN_LAYOUT_PATH = "storage-layouts/manifest.json";
    uint256 internal constant MAX_ENTRIES = 64;

    address internal moduleOwner = address(0xA11CE);
    address internal proxyAdminOwner = address(0xAD0317);

    string internal manifestJson;
    NamespacedSentinelModuleV1 internal implV1;
    NamespacedSentinelModuleV2 internal implV2;

    function setUp() public {
        manifestJson = vm.readFile(MANIFEST_PATH);
        require(vm.keyExistsJson(manifestJson, "$.modules"), "namespace manifest missing modules");
        implV1 = new NamespacedSentinelModuleV1();
        implV2 = new NamespacedSentinelModuleV2();
    }

    // ---------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------

    function _erc7201(string memory id) internal pure returns (bytes32) {
        return keccak256(abi.encode(uint256(keccak256(bytes(id))) - 1)) & ~bytes32(uint256(0xff));
    }

    function _eip1967(string memory id) internal pure returns (bytes32) {
        return bytes32(uint256(keccak256(bytes(id))) - 1);
    }

    function _isReserved(bytes32 slot) internal pure returns (bool) {
        return slot == ERC1967Utils.IMPLEMENTATION_SLOT || slot == ERC1967Utils.ADMIN_SLOT
            || slot == ERC1967Utils.BEACON_SLOT;
    }

    function _path(string memory prefix, uint256 index, string memory suffix) internal pure returns (string memory) {
        return string.concat(prefix, "[", vm.toString(index), "]", suffix);
    }

    function _load(address target, bytes32 slot) internal view returns (bytes32) {
        return vm.load(target, slot);
    }

    function _loadAddress(address target, bytes32 slot) internal view returns (address) {
        return address(uint160(uint256(vm.load(target, slot))));
    }

    function _namespaceSlot(string memory id) internal view returns (bytes32 slot) {
        for (uint256 i = 0; i < MAX_ENTRIES; i++) {
            string memory base = _path(".namespaces", i, "");
            if (!vm.keyExistsJson(manifestJson, base)) break;
            if (keccak256(bytes(vm.parseJsonString(manifestJson, string.concat(base, ".id")))) == keccak256(bytes(id))) {
                return vm.parseJsonBytes32(manifestJson, string.concat(base, ".slot"));
            }
        }
        revert(string.concat("namespace not in manifest: ", id));
    }

    function _sentinels(
        uint256 linearValue,
        bytes32 linearTag,
        uint256 mappingKey,
        uint256 linearMapped,
        uint256 namespacedCounter,
        bytes32 namespacedTag,
        address namespacedAccount,
        uint256 namespacedMapped
    ) internal pure returns (SentinelValues memory) {
        return SentinelValues({
            linearValue: linearValue,
            linearTag: linearTag,
            mappingKey: mappingKey,
            linearMapped: linearMapped,
            namespacedCounter: namespacedCounter,
            namespacedTag: namespacedTag,
            namespacedAccount: namespacedAccount,
            namespacedMapped: namespacedMapped
        });
    }

    function _assertSentinels(address proxy, SentinelValues memory expected) internal view {
        SentinelValues memory actual = NamespacedSentinelModuleV1(proxy).readSentinels(expected.mappingKey);
        assertEq(actual.linearValue, expected.linearValue, "linear value");
        assertEq(actual.linearTag, expected.linearTag, "linear tag");
        assertEq(actual.linearMapped, expected.linearMapped, "linear mapping");
        assertEq(actual.namespacedCounter, expected.namespacedCounter, "namespaced counter");
        assertEq(actual.namespacedTag, expected.namespacedTag, "namespaced tag");
        assertEq(actual.namespacedAccount, expected.namespacedAccount, "namespaced account");
        assertEq(actual.namespacedMapped, expected.namespacedMapped, "namespaced mapping");
        assertEq(NamespacedSentinelModuleV1(proxy).owner(), moduleOwner, "owner");
    }

    function _deployUups() internal returns (address) {
        return address(new ERC1967Proxy(address(implV1), abi.encodeCall(NamespacedSentinelModuleV1.initialize, (moduleOwner))));
    }

    // ---------------------------------------------------------------------
    // 1. Reserved slots
    // ---------------------------------------------------------------------

    function test_ReservedSlotsMatchErc1967AndManifest() public view {
        assertEq(ERC1967Utils.IMPLEMENTATION_SLOT, _eip1967("eip1967.proxy.implementation"));
        assertEq(ERC1967Utils.ADMIN_SLOT, _eip1967("eip1967.proxy.admin"));
        assertEq(ERC1967Utils.BEACON_SLOT, _eip1967("eip1967.proxy.beacon"));

        uint256 count;
        for (uint256 i = 0; i < MAX_ENTRIES; i++) {
            string memory base = _path(".reservedSlots", i, "");
            if (!vm.keyExistsJson(manifestJson, base)) break;
            string memory id = vm.parseJsonString(manifestJson, string.concat(base, ".id"));
            bytes32 slot = vm.parseJsonBytes32(manifestJson, string.concat(base, ".slot"));
            assertEq(slot, _eip1967(id), "reserved slot must derive from its id");
            assertTrue(_isReserved(slot), "manifest reserved slot must be an ERC-1967 constant");
            count++;
        }
        assertEq(count, 3, "implementation, admin and beacon slots are all reserved");
    }

    // ---------------------------------------------------------------------
    // 2. Namespace derivations and per-module composition
    // ---------------------------------------------------------------------

    function test_Erc7201NamespaceSlotsMatchManifest() public view {
        uint256 count;
        for (uint256 i = 0; i < MAX_ENTRIES; i++) {
            string memory base = _path(".namespaces", i, "");
            if (!vm.keyExistsJson(manifestJson, base)) break;
            string memory id = vm.parseJsonString(manifestJson, string.concat(base, ".id"));
            bytes32 slot = vm.parseJsonBytes32(manifestJson, string.concat(base, ".slot"));
            assertEq(slot, _erc7201(id), "namespace slot must follow the ERC-7201 formula");
            assertEq(uint256(slot) & 0xff, 0, "namespace root must be 256-aligned");
            assertFalse(_isReserved(slot), "namespace must not reuse a proxy reserved slot");
            count++;
        }
        assertGt(count, 0, "manifest must inventory the composed OpenZeppelin namespaces");
        assertEq(_namespaceSlot("openzeppelin.storage.Initializable"), 0xf0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a00);
        assertEq(_namespaceSlot("openzeppelin.storage.ReentrancyGuard"), 0x9b779b17422d0df92223018b32b4d1fa46e071723d6817e2486d003becc55f00);
    }

    function test_SentinelFixtureNamespacesFollowFormula() public {
        SentinelSlotProbe probe = new SentinelSlotProbe();
        assertEq(probe.sentinelSlot(), _erc7201("truthbounty.storage.mocks.SentinelModule"));
        assertEq(probe.extensionSlot(), _erc7201("truthbounty.storage.mocks.SentinelModuleExtension"));
        assertTrue(probe.sentinelSlot() != probe.extensionSlot());
        assertFalse(_isReserved(probe.sentinelSlot()));
        assertFalse(_isReserved(probe.extensionSlot()));
    }

    function test_EveryModuleComposesDistinctNonReservedSlots() public view {
        string[] memory modules = vm.parseJsonKeys(manifestJson, "$.modules");
        string[] memory frozen = vm.parseJsonKeys(vm.readFile(FROZEN_LAYOUT_PATH), "$.contracts");
        assertEq(modules.length, frozen.length, "every V2-SC-121 frozen module needs a namespace manifest entry");

        for (uint256 m = 0; m < modules.length; m++) {
            string memory moduleBase = string.concat(".modules.", modules[m]);
            bytes32[] memory slots = new bytes32[](MAX_ENTRIES * 2);
            uint256 n;
            for (uint256 i = 0; i < MAX_ENTRIES; i++) {
                string memory p = _path(string.concat(moduleBase, ".namespaces"), i, "");
                if (!vm.keyExistsJson(manifestJson, p)) break;
                bytes32 slot = vm.parseJsonBytes32(manifestJson, string.concat(p, ".slot"));
                assertEq(slot, _erc7201(vm.parseJsonString(manifestJson, string.concat(p, ".id"))));
                slots[n++] = slot;
            }
            for (uint256 i = 0; i < MAX_ENTRIES; i++) {
                string memory p = _path(string.concat(moduleBase, ".unstructuredSlots"), i, "");
                if (!vm.keyExistsJson(manifestJson, p)) break;
                slots[n++] = vm.parseJsonBytes32(manifestJson, string.concat(p, ".slot"));
            }
            for (uint256 i = 0; i < n; i++) {
                assertFalse(_isReserved(slots[i]), string.concat(modules[m], ": reserved slot reuse"));
                for (uint256 j = i + 1; j < n; j++) {
                    assertTrue(slots[i] != slots[j], string.concat(modules[m], ": overlapping computed slots"));
                }
            }
            string[] memory reserved =
                vm.parseJsonStringArray(manifestJson, string.concat(moduleBase, ".reservedSlots"));
            assertEq(reserved.length, 3, string.concat(modules[m], ": reserved slots must be tracked"));
        }
    }

    // ---------------------------------------------------------------------
    // 3. Manifest slot is the slot OpenZeppelin writes
    // ---------------------------------------------------------------------

    function test_InitializableNamespaceIsTheLiveSlot() public {
        address proxy = _deployUups();
        bytes32 slot = _namespaceSlot("openzeppelin.storage.Initializable");
        assertEq(uint64(uint256(_load(proxy, slot))), 1, "initialized version lives in the manifest slot");
        assertEq(NamespacedSentinelModuleV1(proxy).initializedVersion(), 1);

        vm.prank(moduleOwner);
        NamespacedSentinelModuleV1(proxy).upgradeToAndCall(
            address(implV2), abi.encodeCall(NamespacedSentinelModuleV2.initializeV2, (uint256(0)))
        );
        assertEq(uint64(uint256(_load(proxy, slot))), 2, "reinitializer(2) is recorded in the same slot");
    }

    // ---------------------------------------------------------------------
    // 4. Sentinel-state upgrades and proxy slot protection
    // ---------------------------------------------------------------------

    function testFuzz_UupsUpgradePreservesSentinels(
        uint256 linearValue,
        bytes32 linearTag,
        uint256 mappingKey,
        uint256 linearMapped,
        uint256 namespacedCounter,
        bytes32 namespacedTag,
        address namespacedAccount,
        uint256 namespacedMapped,
        uint256 appendedValue,
        uint256 appendedCounter,
        bytes32 appendedTag
    ) public {
        SentinelValues memory values = _sentinels(
            linearValue, linearTag, mappingKey, linearMapped, namespacedCounter, namespacedTag, namespacedAccount, namespacedMapped
        );
        address proxy = _deployUups();
        vm.prank(moduleOwner);
        NamespacedSentinelModuleV1(proxy).writeSentinels(values);

        assertEq(_loadAddress(proxy, ERC1967Utils.IMPLEMENTATION_SLOT), address(implV1));
        assertEq(_load(proxy, ERC1967Utils.ADMIN_SLOT), bytes32(0), "UUPS proxy has no admin");
        assertEq(_load(proxy, ERC1967Utils.BEACON_SLOT), bytes32(0), "UUPS proxy has no beacon");
        bytes32[4] memory linearBefore;
        for (uint256 s = 0; s < 4; s++) {
            linearBefore[s] = _load(proxy, bytes32(s));
        }

        vm.prank(moduleOwner);
        NamespacedSentinelModuleV1(proxy).upgradeToAndCall(
            address(implV2), abi.encodeCall(NamespacedSentinelModuleV2.initializeV2, (appendedValue))
        );

        _assertSentinels(proxy, values);
        for (uint256 s = 0; s < 4; s++) {
            assertEq(_load(proxy, bytes32(s)), linearBefore[s], "frozen linear slot moved");
        }
        assertEq(_loadAddress(proxy, ERC1967Utils.IMPLEMENTATION_SLOT), address(implV2));
        assertEq(_load(proxy, ERC1967Utils.ADMIN_SLOT), bytes32(0));
        assertEq(_load(proxy, ERC1967Utils.BEACON_SLOT), bytes32(0));
        assertEq(NamespacedSentinelModuleV2(proxy).version(), 2);
        assertEq(NamespacedSentinelModuleV2(proxy).appendedValue(), appendedValue);
        assertEq(uint256(_load(proxy, bytes32(uint256(4)))), appendedValue, "appended variable uses the first gap slot");

        // The appended namespace is independent of every existing value.
        vm.prank(moduleOwner);
        NamespacedSentinelModuleV2(proxy).writeAppended(appendedCounter, appendedTag);
        _assertSentinels(proxy, values);
        (uint256 counter, bytes32 tag) = NamespacedSentinelModuleV2(proxy).readAppended();
        assertEq(counter, appendedCounter);
        assertEq(tag, appendedTag);
        assertEq(NamespacedSentinelModuleV2(proxy).appendedValue(), appendedValue);
    }

    function testFuzz_TransparentUpgradePreservesSentinelsAndAdminSlot(
        uint256 linearValue,
        bytes32 linearTag,
        uint256 mappingKey,
        uint256 linearMapped,
        uint256 namespacedCounter,
        bytes32 namespacedTag,
        address namespacedAccount,
        uint256 namespacedMapped,
        uint256 appendedValue
    ) public {
        SentinelValues memory values = _sentinels(
            linearValue, linearTag, mappingKey, linearMapped, namespacedCounter, namespacedTag, namespacedAccount, namespacedMapped
        );
        TransparentUpgradeableProxy proxy = new TransparentUpgradeableProxy(
            address(implV1), proxyAdminOwner, abi.encodeCall(NamespacedSentinelModuleV1.initialize, (moduleOwner))
        );
        address admin = _loadAddress(address(proxy), ERC1967Utils.ADMIN_SLOT);
        assertTrue(admin != address(0) && admin.code.length > 0, "transparent proxy records its ProxyAdmin");

        vm.prank(moduleOwner);
        NamespacedSentinelModuleV1(address(proxy)).writeSentinels(values);
        assertEq(_loadAddress(address(proxy), ERC1967Utils.ADMIN_SLOT), admin, "implementation writes must not touch the admin slot");
        assertEq(_loadAddress(address(proxy), ERC1967Utils.IMPLEMENTATION_SLOT), address(implV1));

        vm.prank(proxyAdminOwner);
        ProxyAdmin(admin).upgradeAndCall(
            ITransparentUpgradeableProxy(address(proxy)),
            address(implV2),
            abi.encodeCall(NamespacedSentinelModuleV2.initializeV2, (appendedValue))
        );

        _assertSentinels(address(proxy), values);
        assertEq(_loadAddress(address(proxy), ERC1967Utils.ADMIN_SLOT), admin, "upgrade must preserve the admin slot");
        assertEq(_loadAddress(address(proxy), ERC1967Utils.IMPLEMENTATION_SLOT), address(implV2));
        assertEq(NamespacedSentinelModuleV2(address(proxy)).appendedValue(), appendedValue);
    }

    function testFuzz_ImplementationWritesNeverTouchReservedSlots(
        uint256 linearValue,
        bytes32 linearTag,
        uint256 mappingKey,
        uint256 namespacedCounter,
        bytes32 namespacedTag,
        address namespacedAccount
    ) public {
        address proxy = _deployUups();
        // Adversarial payloads: write the reserved slot words themselves as values.
        SentinelValues memory values = _sentinels(
            linearValue,
            linearTag,
            mappingKey,
            uint256(ERC1967Utils.IMPLEMENTATION_SLOT),
            namespacedCounter,
            namespacedTag,
            namespacedAccount,
            uint256(ERC1967Utils.ADMIN_SLOT)
        );
        vm.record();
        vm.prank(moduleOwner);
        NamespacedSentinelModuleV1(proxy).writeSentinels(values);
        (, bytes32[] memory writes) = vm.accesses(proxy);
        assertGt(writes.length, 0);
        for (uint256 i = 0; i < writes.length; i++) {
            assertFalse(_isReserved(writes[i]), "module storage wrote a proxy reserved slot");
        }
        assertEq(_loadAddress(proxy, ERC1967Utils.IMPLEMENTATION_SLOT), address(implV1));
        assertEq(_load(proxy, ERC1967Utils.ADMIN_SLOT), bytes32(0));
        assertEq(_load(proxy, ERC1967Utils.BEACON_SLOT), bytes32(0));
        _assertSentinels(proxy, values);
    }

    // ---------------------------------------------------------------------
    // 5. What the static checker prevents
    // ---------------------------------------------------------------------

    function testFuzz_ReorderedLayoutCorruptsSentinels(uint256 linearValue, bytes32 linearTag) public {
        vm.assume(bytes32(linearValue) != linearTag);
        address proxy = _deployUups();
        SentinelValues memory values = _sentinels(linearValue, linearTag, 0, 0, 0, bytes32(0), address(0), 0);
        vm.prank(moduleOwner);
        NamespacedSentinelModuleV1(proxy).writeSentinels(values);

        ReorderedSentinelModule reordered = new ReorderedSentinelModule();
        vm.prank(moduleOwner);
        NamespacedSentinelModuleV1(proxy).upgradeToAndCall(address(reordered), bytes(""));

        // Slots did not move, the declarations did: every read now returns the other variable.
        assertEq(ReorderedSentinelModule(proxy).linearValue(), uint256(linearTag));
        assertEq(ReorderedSentinelModule(proxy).linearTag(), bytes32(linearValue));
        assertTrue(ReorderedSentinelModule(proxy).linearValue() != linearValue, "reorder must be observable");
    }

    function test_ReservedSlotOverwriteBricksProxy() public {
        address proxy = _deployUups();
        ReservedSlotClobberingModule clobber = new ReservedSlotClobberingModule();
        vm.prank(moduleOwner);
        NamespacedSentinelModuleV1(proxy).upgradeToAndCall(address(clobber), bytes(""));
        assertEq(_loadAddress(proxy, ERC1967Utils.IMPLEMENTATION_SLOT), address(clobber));

        address hijacked = address(0xDEAD);
        ReservedSlotClobberingModule(proxy).clobberImplementationSlot(hijacked);
        assertEq(_loadAddress(proxy, ERC1967Utils.IMPLEMENTATION_SLOT), hijacked, "implementation slot overwritten");

        // The proxy now delegates to an address without code: every call silently returns nothing.
        (bool ok, bytes memory ret) = proxy.call(abi.encodeCall(NamespacedSentinelModuleV1.version, ()));
        assertTrue(ok);
        assertEq(ret.length, 0, "module logic is gone after a reserved-slot overwrite");
    }
}
